Repository operate-first/continuous-delivery, pull requests merged in 2021-11, with the labels that each got.

#15 setup tekton chains instance deployment on op1st
  OWNERS
  tekton-chains/LICENSE
  tekton-chains/README.md
  tekton-chains/base/chains-config.yaml
  tekton-chains/base/config-logging.yaml
  tekton-chains/base/kustomization.yaml
  tekton-chains/base/signing-secrets.yaml
  tekton-chains/base/tekton-chains-controller.yaml
  tekton-chains/overlays/moc/chains-controller-leaderelection-rbac.yaml
  tekton-chains/overlays/moc/chains-controller-sa.yaml
  tekton-chains/overlays/moc/chains-leader-election-roles.yaml
  tekton-chains/overlays/moc/kustomization.yaml
Labels: approved, size/L, lgtm

#17 update onboard template
  .github/ISSUE_TEMPLATE/onboard_aicoe_project.md
Labels: approved, size/XS

#19 use https based url in the pre-commit
  .pre-commit-config.yaml
Labels: approved, size/XS, lgtm
