Repository operate-first/continuous-delivery, pull requests merged in 2022-01, with the labels that each got.

#22 commit of secret items for chains
  tekton-chains/overlays/moc/.sops.yaml
  tekton-chains/overlays/moc/kustomization.yaml
  tekton-chains/overlays/moc/tekton-chain-secret-generator.yaml
  tekton-chains/overlays/moc/tekton-chains-secret.enc.yaml
Labels: approved, size/M

#24 Tekton chains: required items to work correctly
  tekton-chains/README.md
  tekton-chains/base/chains-anyuid-rolebinding.yaml
  tekton-chains/base/chains-config.yaml
  tekton-chains/base/kustomization.yaml
  tekton-chains/base/signing-secrets.yaml
  tekton-chains/base/tekton-chains-controller.yaml
Labels: approved, size/M

#26 setup prow pre-submit job on the repo
  .prow.yaml
Labels: size/M

#27 :lock: setup cosign signing secrets for tekton chains
  .gitignore
  tekton-chains/.sops.yaml
  tekton-chains/overlays/moc/tekton-chain-secret-generator.yaml
  tekton-chains/overlays/moc/tekton-chains-secret.enc.yaml
  tekton-chains/overlays/moc/tekton-chains-secrets.enc.yaml
Labels: approved, size/M, lgtm
